/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yanglin_ongoingdemo1_testJni */

#ifndef _Included_com_example_yanglin_ongoingdemo1_testJni
#define _Included_com_example_yanglin_ongoingdemo1_testJni
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
